server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Đường dẫn cho User Service (Mở cửa tự do)
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        # Đường dẫn cho Product Service (BẢO MẬT)
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
