server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Đường dẫn cho User Service (Mở cửa tự do)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        # Đường dẫn cho Product Service (BẢO MẬT)
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        # Đường dẫn cho Order Service (BẢO MẬT)
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
