# Discovery Server Port
server.port=8761

# TẮT TỰ ĐĂNG KÝ (Vì chính nó là Server, không cần tự đăng ký lên bản thân)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# TÊN ỨNG DỤNG
spring.application.name=discovery-server
