# ============================================
# USER SERVICE - PORT 8081
# ============================================
spring.application.name=user-service
server.port=8081

# KẾT NỐI DATABASE GEARHOST (ONLINE)
spring.datasource.url=jdbc:sqlserver://den1.mssql8.gear.host:1433;databaseName=microservices;encrypt=true;trustServerCertificate=true;loginTimeout=30
spring.datasource.username=microservices
spring.datasource.password=Jl3t~spA8_C5
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# EUREKA DISCOVERY
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
